# NumPy and Pandas Assignment
Complete the following tasks by filling in the code where indicated.
Ensure your notebook is well-documented with markdown cells explaining your code and results.

In [3]:
## Import necessary ibraries

In [4]:
# Import necessary libraries
import numpy as np
import pandas as pd

## Task 1: NumPy Basics


### 1.1. Array Creation

In [7]:
# Create a 1D and a 2D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### 1.2. Array Operations

In [9]:
# Perform basic arithmetic operations on the arrays
arr_1d_add = arr_1d + 10
arr_2d_mult = arr_2d * 2
print("1D Array + 10:", arr_1d_add)
print("2D Array * 2:\n", arr_2d_mult)

1D Array + 10: [11 12 13 14 15]
2D Array * 2:
 [[ 2  4  6]
 [ 8 10 12]]


### 1.3. Indexing and Slicing

In [11]:
## Demonstrate indexing and slicing on the arrays
print("First element of 1D array:", arr_1d[0])
print("First row of 2D array:\n", arr_2d[0, :])

First element of 1D array: 1
First row of 2D array:
 [1 2 3]


### 1.4. Shape and reshape

In [13]:
# Show how to check the shape of an array and reshape it
print("Shape of 2D array:", arr_2d.shape)
reshaped_arr = arr_2d.reshape((3, 2))
print("Reshaped 2D Array:\n", reshaped_arr)

Shape of 2D array: (2, 3)
Reshaped 2D Array:
 [[1 2]
 [3 4]
 [5 6]]


# Task 2: Pandas Basics

### 2.1. Series and DataFrame Creation

In [16]:
# Create a Pandas Series and DataFrame
s = pd.Series([1, 2, 3, 4, 5])
print("Pandas Series:\n", s)

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
print("Pandas DataFrame:\n", df)

Pandas Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Pandas DataFrame:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


### 2.2. Reading Data

In [18]:
# Read data from a CSV file (ensure you have a sample CSV file in your repository)
df_read = pd.read_csv('sample_data.csv')
print("Read DataFrame from CSV:\n", df_read)

Read DataFrame from CSV:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


### 2.3. Data Inspection

In [20]:
# Perform basic data inspection methods
print("Head of DataFrame:\n", df.head())
print("Info of DataFrame:\n", df.info())
print("Description of DataFrame:\n", df.describe())

Head of DataFrame:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
Info of DataFrame:
 None
Description of DataFrame:
          A    B    C
count  3.0  3.0  3.0
mean   2.0  5.0  8.0
std    1.0  1.0  1.0
min    1.0  4.0  7.0
25%    1.5  4.5  7.5
50%    2.0  5.0  8.0
75%    2.5  5.5  8.5
max    3.0  6.0  9.0


### 2.4. Data Manipulation

In [22]:
# Selecting Data
print("Column A:\n", df['A'])
print("Columns A and B:\n", df[['A', 'B']])

# Filtering Data
filtered_df = df[df['A'] > 1]
print("Filtered DataFrame (A > 1):\n", filtered_df)

# Adding/Removing Columns
df['D'] = df['A'] + df['B']
print("DataFrame with new column D:\n", df)
df.drop('D', axis=1, inplace=True)
print("DataFrame after dropping column D:\n", df)

# Handling Missing Data
df_with_nan = df.copy()
df_with_nan.loc[1, 'B'] = np.nan
print("DataFrame with NaN:\n", df_with_nan)
print("DataFrame after dropping NaN:\n", df_with_nan.dropna())
print("DataFrame after filling NaN with 0:\n", df_with_nan.fillna(0))

Column A:
 0    1
1    2
2    3
Name: A, dtype: int64
Columns A and B:
    A  B
0  1  4
1  2  5
2  3  6
Filtered DataFrame (A > 1):
    A  B  C
1  2  5  8
2  3  6  9
DataFrame with new column D:
    A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9
DataFrame after dropping column D:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
DataFrame with NaN:
    A    B  C
0  1  4.0  7
1  2  NaN  8
2  3  6.0  9
DataFrame after dropping NaN:
    A    B  C
0  1  4.0  7
2  3  6.0  9
DataFrame after filling NaN with 0:
    A    B  C
0  1  4.0  7
1  2  0.0  8
2  3  6.0  9


# Task 3: Data Analysis with Pandas

In [24]:
# Aggregations
print("Mean of column A:", df['A'].mean())
print("Sum of column A:", df['A'].sum())

# Merging and Joining
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
merged_df = pd.merge(df1, df2, on='key', how='inner')
print("Merged DataFrame:\n", merged_df)

# Pivot Tables
pivot_df = df.pivot_table(values='C', index='A', columns='B', aggfunc='mean')
print("Pivot Table:\n", pivot_df)

# Time Series Analysis
df['date'] = pd.date_range(start='1/1/2020', periods=len(df), freq='D')
df.set_index('date', inplace=True)
print("DataFrame with Date Index:\n", df)
resampled_df = df.resample('M').mean()
print("Resampled DataFrame:\n", resampled_df)

Mean of column A: 2.0
Sum of column A: 6
Merged DataFrame:
   key  value_x  value_y
0   A        1        4
1   B        2        5
Pivot Table:
 B    4    5    6
A               
1  7.0  NaN  NaN
2  NaN  8.0  NaN
3  NaN  NaN  9.0
DataFrame with Date Index:
             A  B  C
date               
2020-01-01  1  4  7
2020-01-02  2  5  8
2020-01-03  3  6  9
Resampled DataFrame:
               A    B    C
date                     
2020-01-31  2.0  5.0  8.0
